version: '3.5'

services:
  zookeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./kafka/zoo/data:/data
      - ./kafka/zoo/datalog:/datalog
    networks:
      titan_network:
        ipv4_address: 192.168.100.10

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeper
    networks:
      titan_network:
        ipv4_address: 192.168.100.20

networks:
  titan_network:
    name: titan_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  log-volume: